package com.example.beautysalon.mbg.mapper;

import com.example.beautysalon.mbg.model.Balance;
import com.example.beautysalon.mbg.model.BalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    long countByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int deleteByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int insert(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int insertSelective(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    List<Balance> selectByExample(BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    Balance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") Balance record, @Param("example") BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByExample(@Param("record") Balance record, @Param("example") BalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByPrimaryKeySelective(Balance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByPrimaryKey(Balance record);
}