package com.example.beautysalon.mbg.mapper;

import com.example.beautysalon.mbg.model.BusinessHours;
import com.example.beautysalon.mbg.model.BusinessHoursExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessHoursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    long countByExample(BusinessHoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int deleteByExample(BusinessHoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int insert(BusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int insertSelective(BusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    List<BusinessHours> selectByExample(BusinessHoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    BusinessHours selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") BusinessHours record, @Param("example") BusinessHoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int updateByExample(@Param("record") BusinessHours record, @Param("example") BusinessHoursExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int updateByPrimaryKeySelective(BusinessHours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_hours
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    int updateByPrimaryKey(BusinessHours record);
}