package com.example.beautysalon.mbg.mapper;

import com.example.beautysalon.mbg.model.CouponDistribution;
import com.example.beautysalon.mbg.model.CouponDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    long countByExample(CouponDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int deleteByExample(CouponDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int insert(CouponDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int insertSelective(CouponDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    List<CouponDistribution> selectByExample(CouponDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    CouponDistribution selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") CouponDistribution record, @Param("example") CouponDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByExample(@Param("record") CouponDistribution record, @Param("example") CouponDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByPrimaryKeySelective(CouponDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_distribution
     *
     * @mbg.generated Thu May 13 00:55:17 CST 2021
     */
    int updateByPrimaryKey(CouponDistribution record);
}