package com.example.beautysalon.mbg.mapper;

import com.example.beautysalon.mbg.model.Evaluation;
import com.example.beautysalon.mbg.model.EvaluationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    long countByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int deleteByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int insertSelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    List<Evaluation> selectByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    Evaluation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByExample(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByPrimaryKeySelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByPrimaryKey(Evaluation record);
}