package com.example.beautysalon.mbg.mapper;

import com.example.beautysalon.mbg.model.Stylist;
import com.example.beautysalon.mbg.model.StylistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StylistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    long countByExample(StylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int deleteByExample(StylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int deleteByPrimaryKey(Integer stylistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int insert(Stylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int insertSelective(Stylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    List<Stylist> selectByExample(StylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    Stylist selectByPrimaryKey(Integer stylistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") Stylist record, @Param("example") StylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByExample(@Param("record") Stylist record, @Param("example") StylistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByPrimaryKeySelective(Stylist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    int updateByPrimaryKey(Stylist record);
}