package com.example.beautysalon.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Balance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.payments
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Float payments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.type
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.description
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table balance
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.id
     *
     * @return the value of balance.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.id
     *
     * @param id the value for balance.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.payments
     *
     * @return the value of balance.payments
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Float getPayments() {
        return payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.payments
     *
     * @param payments the value for balance.payments
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setPayments(Float payments) {
        this.payments = payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.type
     *
     * @return the value of balance.type
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.type
     *
     * @param type the value for balance.type
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.create_date
     *
     * @return the value of balance.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.create_date
     *
     * @param createDate the value for balance.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.description
     *
     * @return the value of balance.description
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.description
     *
     * @param description the value for balance.description
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.user_id
     *
     * @return the value of balance.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.user_id
     *
     * @param userId the value for balance.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payments=").append(payments);
        sb.append(", type=").append(type);
        sb.append(", createDate=").append(createDate);
        sb.append(", description=").append(description);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}