package com.example.beautysalon.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.order_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.stylist_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer stylistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.contact
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.rate
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.order_id
     *
     * @return the value of comment.order_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.order_id
     *
     * @param orderId the value for comment.order_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.stylist_id
     *
     * @return the value of comment.stylist_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getStylistId() {
        return stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.stylist_id
     *
     * @param stylistId the value for comment.stylist_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setStylistId(Integer stylistId) {
        this.stylistId = stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.contact
     *
     * @return the value of comment.contact
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.contact
     *
     * @param contact the value for comment.contact
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_date
     *
     * @return the value of comment.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_date
     *
     * @param createDate the value for comment.create_date
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.rate
     *
     * @return the value of comment.rate
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.rate
     *
     * @param rate the value for comment.rate
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Wed Apr 14 15:46:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", stylistId=").append(stylistId);
        sb.append(", contact=").append(contact);
        sb.append(", createDate=").append(createDate);
        sb.append(", userId=").append(userId);
        sb.append(", rate=").append(rate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}