package com.example.beautysalon.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Coupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.user_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.up_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer upTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.valid_date_from
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Date validDateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.valid_date_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Date validDateTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.receive_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Date receiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.used_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Date usedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.is_used
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.type
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.id
     *
     * @return the value of coupon.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.id
     *
     * @param id the value for coupon.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.user_id
     *
     * @return the value of coupon.user_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.user_id
     *
     * @param userId the value for coupon.user_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_id
     *
     * @return the value of coupon.coupon_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_id
     *
     * @param couponId the value for coupon.coupon_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.value
     *
     * @return the value of coupon.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.value
     *
     * @param value the value for coupon.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.up_to
     *
     * @return the value of coupon.up_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getUpTo() {
        return upTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.up_to
     *
     * @param upTo the value for coupon.up_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setUpTo(Integer upTo) {
        this.upTo = upTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.valid_date_from
     *
     * @return the value of coupon.valid_date_from
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Date getValidDateFrom() {
        return validDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.valid_date_from
     *
     * @param validDateFrom the value for coupon.valid_date_from
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setValidDateFrom(Date validDateFrom) {
        this.validDateFrom = validDateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.valid_date_to
     *
     * @return the value of coupon.valid_date_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Date getValidDateTo() {
        return validDateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.valid_date_to
     *
     * @param validDateTo the value for coupon.valid_date_to
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setValidDateTo(Date validDateTo) {
        this.validDateTo = validDateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.receive_date
     *
     * @return the value of coupon.receive_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Date getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.receive_date
     *
     * @param receiveDate the value for coupon.receive_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.used_date
     *
     * @return the value of coupon.used_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Date getUsedDate() {
        return usedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.used_date
     *
     * @param usedDate the value for coupon.used_date
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setUsedDate(Date usedDate) {
        this.usedDate = usedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.is_used
     *
     * @return the value of coupon.is_used
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.is_used
     *
     * @param isUsed the value for coupon.is_used
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setIsUsed(Integer isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.type
     *
     * @return the value of coupon.type
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.type
     *
     * @param type the value for coupon.type
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", couponId=").append(couponId);
        sb.append(", value=").append(value);
        sb.append(", upTo=").append(upTo);
        sb.append(", validDateFrom=").append(validDateFrom);
        sb.append(", validDateTo=").append(validDateTo);
        sb.append(", receiveDate=").append(receiveDate);
        sb.append(", usedDate=").append(usedDate);
        sb.append(", isUsed=").append(isUsed);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}