package com.example.beautysalon.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Reserve implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.user_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.stylist_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer stylistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.status
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.create_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.pay_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.serve_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Date serveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.total
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Float total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.points
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.coupon
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer coupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.value
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Float value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.services
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private String services;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.takeUp
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer takeup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.is_rewarded
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private Integer isRewarded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reserve
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.id
     *
     * @return the value of reserve.id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.id
     *
     * @param id the value for reserve.id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.user_id
     *
     * @return the value of reserve.user_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.user_id
     *
     * @param userId the value for reserve.user_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.stylist_id
     *
     * @return the value of reserve.stylist_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getStylistId() {
        return stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.stylist_id
     *
     * @param stylistId the value for reserve.stylist_id
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setStylistId(Integer stylistId) {
        this.stylistId = stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.status
     *
     * @return the value of reserve.status
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.status
     *
     * @param status the value for reserve.status
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.create_date
     *
     * @return the value of reserve.create_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.create_date
     *
     * @param createDate the value for reserve.create_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.pay_date
     *
     * @return the value of reserve.pay_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.pay_date
     *
     * @param payDate the value for reserve.pay_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.serve_date
     *
     * @return the value of reserve.serve_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Date getServeDate() {
        return serveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.serve_date
     *
     * @param serveDate the value for reserve.serve_date
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setServeDate(Date serveDate) {
        this.serveDate = serveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.total
     *
     * @return the value of reserve.total
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.total
     *
     * @param total the value for reserve.total
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.points
     *
     * @return the value of reserve.points
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.points
     *
     * @param points the value for reserve.points
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.coupon
     *
     * @return the value of reserve.coupon
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.coupon
     *
     * @param coupon the value for reserve.coupon
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setCoupon(Integer coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.value
     *
     * @return the value of reserve.value
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Float getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.value
     *
     * @param value the value for reserve.value
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setValue(Float value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.services
     *
     * @return the value of reserve.services
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public String getServices() {
        return services;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.services
     *
     * @param services the value for reserve.services
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setServices(String services) {
        this.services = services;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.takeUp
     *
     * @return the value of reserve.takeUp
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getTakeup() {
        return takeup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.takeUp
     *
     * @param takeup the value for reserve.takeUp
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setTakeup(Integer takeup) {
        this.takeup = takeup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.is_rewarded
     *
     * @return the value of reserve.is_rewarded
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public Integer getIsRewarded() {
        return isRewarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.is_rewarded
     *
     * @param isRewarded the value for reserve.is_rewarded
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    public void setIsRewarded(Integer isRewarded) {
        this.isRewarded = isRewarded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve
     *
     * @mbg.generated Tue May 11 23:32:11 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", stylistId=").append(stylistId);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", payDate=").append(payDate);
        sb.append(", serveDate=").append(serveDate);
        sb.append(", total=").append(total);
        sb.append(", points=").append(points);
        sb.append(", coupon=").append(coupon);
        sb.append(", value=").append(value);
        sb.append(", services=").append(services);
        sb.append(", takeup=").append(takeup);
        sb.append(", isRewarded=").append(isRewarded);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}