package com.example.beautysalon.mbg.model;

import java.io.Serializable;

public class Services implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.barbershop_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer barbershopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.name
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.time
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table services
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.id
     *
     * @return the value of services.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.id
     *
     * @param id the value for services.id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.barbershop_id
     *
     * @return the value of services.barbershop_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getBarbershopId() {
        return barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.barbershop_id
     *
     * @param barbershopId the value for services.barbershop_id
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setBarbershopId(Integer barbershopId) {
        this.barbershopId = barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.name
     *
     * @return the value of services.name
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.name
     *
     * @param name the value for services.name
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.value
     *
     * @return the value of services.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.value
     *
     * @param value the value for services.value
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.time
     *
     * @return the value of services.time
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.time
     *
     * @param time the value for services.time
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Wed May 12 15:43:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", barbershopId=").append(barbershopId);
        sb.append(", name=").append(name);
        sb.append(", value=").append(value);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}