package com.example.beautysalon.mbg.model;

import java.io.Serializable;

public class Stylist implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.stylist_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private Integer stylistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.barbershop_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private Integer barbershopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.speciality
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String speciality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.is_passed
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private Integer isPassed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.real_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.working_years
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private Integer workingYears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.stylist_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String stylistName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.phone
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.password
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.avatar
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stylist.role
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stylist
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.stylist_id
     *
     * @return the value of stylist.stylist_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public Integer getStylistId() {
        return stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.stylist_id
     *
     * @param stylistId the value for stylist.stylist_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setStylistId(Integer stylistId) {
        this.stylistId = stylistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.barbershop_id
     *
     * @return the value of stylist.barbershop_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public Integer getBarbershopId() {
        return barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.barbershop_id
     *
     * @param barbershopId the value for stylist.barbershop_id
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setBarbershopId(Integer barbershopId) {
        this.barbershopId = barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.speciality
     *
     * @return the value of stylist.speciality
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.speciality
     *
     * @param speciality the value for stylist.speciality
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.is_passed
     *
     * @return the value of stylist.is_passed
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public Integer getIsPassed() {
        return isPassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.is_passed
     *
     * @param isPassed the value for stylist.is_passed
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setIsPassed(Integer isPassed) {
        this.isPassed = isPassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.real_name
     *
     * @return the value of stylist.real_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.real_name
     *
     * @param realName the value for stylist.real_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.working_years
     *
     * @return the value of stylist.working_years
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public Integer getWorkingYears() {
        return workingYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.working_years
     *
     * @param workingYears the value for stylist.working_years
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setWorkingYears(Integer workingYears) {
        this.workingYears = workingYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.stylist_name
     *
     * @return the value of stylist.stylist_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getStylistName() {
        return stylistName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.stylist_name
     *
     * @param stylistName the value for stylist.stylist_name
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setStylistName(String stylistName) {
        this.stylistName = stylistName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.phone
     *
     * @return the value of stylist.phone
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.phone
     *
     * @param phone the value for stylist.phone
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.password
     *
     * @return the value of stylist.password
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.password
     *
     * @param password the value for stylist.password
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.avatar
     *
     * @return the value of stylist.avatar
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.avatar
     *
     * @param avatar the value for stylist.avatar
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stylist.role
     *
     * @return the value of stylist.role
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stylist.role
     *
     * @param role the value for stylist.role
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stylist
     *
     * @mbg.generated Mon May 03 23:06:28 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stylistId=").append(stylistId);
        sb.append(", barbershopId=").append(barbershopId);
        sb.append(", speciality=").append(speciality);
        sb.append(", isPassed=").append(isPassed);
        sb.append(", realName=").append(realName);
        sb.append(", workingYears=").append(workingYears);
        sb.append(", stylistName=").append(stylistName);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", avatar=").append(avatar);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}