package com.example.beautysalon.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Turnover implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.create_date
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.total
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private Float total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.person
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private Integer person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column turnover.barbershop_id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private Integer barbershopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table turnover
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.id
     *
     * @return the value of turnover.id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.id
     *
     * @param id the value for turnover.id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.create_date
     *
     * @return the value of turnover.create_date
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.create_date
     *
     * @param createDate the value for turnover.create_date
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.total
     *
     * @return the value of turnover.total
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.total
     *
     * @param total the value for turnover.total
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.person
     *
     * @return the value of turnover.person
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.person
     *
     * @param person the value for turnover.person
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public void setPerson(Integer person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column turnover.barbershop_id
     *
     * @return the value of turnover.barbershop_id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public Integer getBarbershopId() {
        return barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column turnover.barbershop_id
     *
     * @param barbershopId the value for turnover.barbershop_id
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    public void setBarbershopId(Integer barbershopId) {
        this.barbershopId = barbershopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table turnover
     *
     * @mbg.generated Wed May 12 19:03:49 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", total=").append(total);
        sb.append(", person=").append(person);
        sb.append(", barbershopId=").append(barbershopId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}